### ISSUE TITLE
Actual package out of sync with source?

### ISSUE THREAD

**Issue by Sandyman** [fliot/py3wetransfer#3]
Hi,
I noticed a discrepancy between the source code in this repository and the source in the actual package. In my case, it's because I couldn't find libmagic in an Alpine Linux docker container. 

It seems the repository has been updated, but the package hasn't? 

I saw that the last commit was somewhere in October last year. Is this package still maintained? 

Thanks, I appreciate the work you've done.

**Comment by fliot** [comment]
Can you ellaborate your thoughs ?
Which discrepancy between source code and package did you observe ?
If there are some, it's obviously an error I have to check.
