### ISSUE TITLE
ImportError: cannot import name 'TransferApi'

### ISSUE THREAD

**Issue by arieltoledo** [fliot/py3wetransfer#7]
Hi, just added the first line of code [ `from wetransfer import TransferApi` ] after install pip package,  and got ImportError: cannot import name 'TransferApi'. 
Not sure whats wrong.

**Comment by Sandyman** [comment]
@arieltoledo Are you by any chance using Python2?

**Comment by arieltoledo** [comment]
@Sandyman Hi. The issue was something related to pip version and the virtualenv. Nothing related to the library. Thanks.
